---
title: "R Notebook"
output: html_notebook
---
Import Dataset and create working dataset:
```{r}
#install.packages("plotly")
library(plotly)
library(reshape2)
games <- read.csv("vgsales.csv")
game_melt <- melt(data=games,id.vars = c("Rank","Name","Platform","Year","Genre","Publisher"),measure.vars=c("NA_Sales","EU_Sales","JP_Sales","Other_Sales","Global_Sales"))
game_melt$Year <- as.factor(game_melt$Year)
colnames(game_melt)[7] <- "Region"
colnames(game_melt)[8] <- "Copies Sold"
head(game_melt)
```
```{r}
game_melt %>% 
    group_by(Region,Year,Genre) %>%
    summarise(net = sum(`Copies Sold`))
```
Graph time baby!
```{r}
#Number of Copies Sold
library(tidyverse)
graph1 <- game_melt %>% 
    filter(Region == "NA_Sales") %>%
    group_by(Region,Year,Genre) %>%
    summarise("Copies Sold" = sum(`Copies Sold`)) %>% 
    ggplot() +
    aes(x=Year,
        y=`Copies Sold`,
        fill = Genre) + 
    geom_bar(stat="identity")+
    theme(axis.text.x = element_text(angle = 90, hjust=0.95, vjust=0.2))+
    ylab("Number of Copies Sold (in millions)")
ggplotly(graph1)
```

```{r}
#Number Releases
library(tidyverse)
graph2 <- game_melt %>% 
    filter(Region == "NA_Sales") %>%
    group_by(Region,Year,Genre) %>%
    count(Year,Genre) %>%
    rename(`Number of Releases`="n")%>% 
    ggplot() +
    aes(x=Year,
        y=`Number of Releases`,
        fill = Genre) + 
    geom_bar(stat="identity")+
    theme(axis.text.x = element_text(angle = 90, hjust=0.95, vjust=0.2))+
    ylab("Number of Games Released")
ggplotly(graph2)
```
```{r}
#Number of Platforms, Genres and Publishers with games > 100 copies sold 
graph3 <- game_melt %>% 
    filter(Region == "JP_Sales") %>%
    group_by(Year)%>%
    melt(id.vars=c("Year"),measure.vars=c("Genre","Platform","Publisher")) %>%
    rename(Category='variable') %>% 
    group_by(Year,Category) %>%
    unique() %>%
    count(Year,Category) %>%
    rename(`Counts of Genres, Publishers and Platforms`= n) %>% 
    ggplot() +
    aes(x=Year,
        y=`Counts of Genres, Publishers and Platforms`,
        fill = Category) + 
    geom_bar(stat="identity")+
    theme(axis.text.x = element_text(angle = 90, hjust=0.95, vjust=0.2))+
    ylab("Counts of Genres, Publishers and Platforms")
ggplotly(graph3)
```

